FROM public.ecr.aws/o7x6j3x6/sd-dreambooth-finetuning-v2


RUN curl -L https://github.com/peak/s5cmd/releases/download/v2.0.0/s5cmd_2.0.0_Linux-64bit.tar.gz | tar -xz && mv s5cmd /opt/conda/bin/

RUN mkdir -p /opt/ml/input/data/images
COPY images/ /opt/ml/input/data/images/

COPY ./sd_code/ /opt/ml/code/

COPY train.sh /opt/ml/code/
COPY train_dreambooth.py /opt/ml/code/


