#!/usr/bin/env python 
import os
import uvicorn


reload=os.environ.get("reload", False)

if __name__ == '__main__':
    uvicorn.run('api_server:app',
                host='0.0.0.0',
                port=8080,
                reload=reload,
                log_level='info')
